### ISSUE TITLE
Implement auto-updates in themes screen

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/wp-autoupdates#10]
_Migrated from: https://github.com/audrasjb/wp-autoupdates/issues/41
Previously opened by: @audrasjb
Original description:_
>- Port auto-update feature to themes screen (for both single site and network)
>- Identify the needed hooks in the single site Themes screen and open a WP Core Trac ticket for that

**Comment by audrasjb** [comment]
Closed with previously merged pull request in version 0.4.0
