### ISSUE TITLE
Translation: Reduce translation effort for similar strings for themes and plugins

### ISSUE THREAD

**Issue by ePascalC** [WordPress/wp-autoupdates#107]
![image](https://user-images.githubusercontent.com/18325208/81083907-750adf80-8ef5-11ea-84a0-36acaf10e949.png)

These could be combined to something like:
/* Translators: %s will be "themes" or "plugins" */
pintf( 'Selected %s will no longer be auto-updates', 'themes' )

**Comment by pbiron** [comment]
thanx for the feedback, much appreciated!

BTW, could you also look at https://github.com/WordPress/wp-autoupdates/pull/103#issuecomment-623757089?

**Comment by pedro-mendonca** [comment]
Not sure if it's a good idea.
Might be a language where the translation is different (eg.: different genre)

**Comment by ePascalC** [comment]
@pedro-mendonca  thanks for the remark.
In French: Theme is male and Plugin is female and it works out well.
In the European languages I know, this would not generate any issues. Do you know any that could generate the issue you describe?

**Comment by pedro-mendonca** [comment]
No, I can only speak for portuguese where both are male and it's not a problem.

**Comment by audrasjb** [comment]
@ePascalC If I'm not wrong, at least in French there will actually be a problem.
Themes: `Les %s sélectionnés seront mis à jour automatiquement`
Plugins: `Les %s sélectionnées seront mises à jour automatiquement`

**Comment by ePascalC** [comment]
@audrasjb You are right !!! and so was @pedro-mendonca 
Can a issue be 'closed as stupid' ?

**Comment by audrasjb** [comment]
Ah ah 🤗

**Comment by pbiron** [comment]
I don't see "stupid" in the available labels, so I chose "Invalid" :-)
