### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/wp-autoupdates#11]
_Migrated from: https://github.com/audrasjb/wp-autoupdates/issues/61
Previously opened by: @rodolphebertozzo
Original description:_
>If I understood correctly, the automatic update feature for themes and plugins should be implemented in Wordpress version 5.5.
Wordpress auto updates will therefore be optimized, operational and ready to be installed on different sites by then?
Or there will be no need for a plugin (these features will be directly integrated into the core of Wordpress) and in this case, what would become of Wordpress auto-updates?

**Comment by jeffpaul** [comment]
_Previously commented by: @audrasjb
Original comment:_
>Hello,
Yes, as an official _Feature Plugin_, this plugin is meant to be integrated into WordPress Core, just like [Health Check](https://wordpress.org/plugins/health-check/).
Once it's merged, this plugin is likely to be used for the work on Core major versions auto-updates, but there is no plan for this at the moment.

**Comment by jeffpaul** [comment]
@audrasjb @rodolphebertozzo it sounds like the original question here has been answered/resolved and we can close this issue, correct?

**Comment by pbiron** [comment]
@jeffpaul yes, this should have been closed a while ago.  Closing it now.
