### ISSUE TITLE
Customize update timeframes

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/wp-autoupdates#12]
_Migrated from: https://github.com/audrasjb/wp-autoupdates/issues/62
Previously opened by: @rodolphebertozzo
Original description:_
>It would be nice to be able to allow users to choose the update periods for plugins and themes, for example right away when the update is available, or some customizable deadlines (2 hours, 12 hours,...).

**Comment by jeffpaul** [comment]
_Previously commented by: @pbiron
Original comment:_
>The updates happen on the `wp_version_check` cron job (which calls [wp_version_check()](https://developer.wordpress.org/reference/functions/wp_version_check/)), which core schedules for twice a day.
>
>Since the scheduling of **all** cron jobs can be filtered with [schedule_event](https://developer.wordpress.org/reference/hooks/schedule_event/), I would say that a feature like you're asking for is "plugin territory".  But that's just my opinion.

**Comment by pbiron** [comment]
I'm going to close this as `wontfix`, as far as the feature plugin is concerned.

@rodolphebertozzo, if you feel strongly about this, then once the core merge has happened you can open a trac ticket about it.
