### ISSUE TITLE
Handle themes auto-updates

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/wp-autoupdates#14]
_Migrated from: https://github.com/audrasjb/wp-autoupdates/issues/65
Previously opened by: @jeffpaul
Original description:_
>If we're going to track plugins auto-updates, we should similarly track themes auto-updates. Noting that this issue may lag the plugins work a bit given the differences between how themes and plugins are maintained on WordPress.org.

**Comment by bookdude13** [comment]
The start of this was handled in:
https://github.com/audrasjb/wp-autoupdates/pull/44 (basis)
https://github.com/audrasjb/wp-autoupdates/pull/78 (themes.php single site)
https://github.com/audrasjb/wp-autoupdates/pull/82 (update-core.php)

**Comment by audrasjb** [comment]
Fixed by:
- audrasjb/wp-autoupdates#44 (basis)
- audrasjb/wp-autoupdates#78 (themes.php single site)
- audrasjb/wp-autoupdates#82 (update-core.php)
- #32 
- #33 
- #36
