### ISSUE TITLE
Validate design for plugins screen

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/wp-autoupdates#17]
_Migrated from: https://github.com/audrasjb/wp-autoupdates/issues/68
Previously opened by: @jeffpaul
Original description:_
>We'll want to ensure the WordPress Design team reviews the plugins screen work and that implementation within this plugin matches those mockups.

**Comment by pbiron** [comment]
We've gotten all the #design review we're going to get during this plugin's development, any further review can happen after the initial core merge, so I'm closing this.

**Comment by jeffpaul** [comment]
@pbiron who did the design review?  We'll want to make sure they're part of the core merge process as there may be questions from the release team about design choices that would be best handled by this person/these people.
