### ISSUE TITLE
Validate design for themes screen

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/wp-autoupdates#18]
_Migrated from: https://github.com/audrasjb/wp-autoupdates/issues/69
Previously opened by: @jeffpaul
Original description:_
>We'll want to ensure the WordPress Design team reviews the themes screen work and that implementation within this plugin matches those mockups.

**Comment by jeffpaul** [comment]
_Previously commented by: @pbiron
Original comment:_
>The latest comment from the [Trac ticket](https://core.trac.wordpress.org/ticket/49199) proposed something like the following for single themes:
><img width="1162" alt="themes_updates_section_at_bottom" src="https://user-images.githubusercontent.com/2818133/77498719-59a0b500-6e1e-11ea-857b-9187c1a1f964.png">
>
>And for multisite we can add a column/standardize to the plugins design, since the screens are so similar.

**Comment by pedro-mendonca** [comment]
It would be a lot easier if the themes screen had some hooks as there are in the plugins screen.

Here is a proposal I did to add some customization possibilities to themes screen, it would be possible to add items to theme info and theme actions.
https://core.trac.wordpress.org/ticket/47650

I've tested this successefully for some customizations, quite similar to these from Auto Updates.

**Comment by pbiron** [comment]
We've gotten all the #design review we're going to get during this plugin's development, any further review can happen after the initial core merge, so I'm closing this.
