### ISSUE TITLE
Validate design for update-core screen

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/wp-autoupdates#19]
_Migrated from: https://github.com/audrasjb/wp-autoupdates/issues/70
Previously opened by: @jeffpaul
Original description:_
>We'll want to ensure the WordPress Design team reviews the update-core screen work and that implementation within this plugin matches those mockups.

**Comment by pbiron** [comment]
We've gotten all the #design review we're going to get during this plugin's development, any further review can happen after the initial core merge, so I'm closing this.
