### ISSUE TITLE
Coding standards audit

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/wp-autoupdates#24]
_Migrated from: https://github.com/audrasjb/wp-autoupdates/issues/75
Previously opened by: @jeffpaul
Original description:_
>While a WPCS audit will be ideal (required?) before submitting for a WordPress core feature plugin merge proposal, we may be even better served to have a pre-commit hook that runs WPCS against our commits. Similarly having WPCS as a PR check via something like GitHub Actions or Travis or whatever is also very worthwhile. Someone want to work on adding that to this repo?

**Comment by pbiron** [comment]
While not done via GitHub actions, this has been addressed, most importantly in #119 and #124, so I'm closing this.
