### ISSUE TITLE
Inline Docs audit

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/wp-autoupdates#25]
_Migrated from: https://github.com/audrasjb/wp-autoupdates/issues/76
Previously opened by: @jeffpaul
Original description:_
>So best case scenario, this plugin is fully self-documenting-code. Realistic scenario? We'll need a close review of the code to ensure we properly include inline docs to ensure if this is merged into WordPress core that we've got the appropriate level of documentation.

**Comment by pbiron** [comment]
This has been addressed in #62 and other subsequent PR, so closing.
