### ISSUE TITLE
Update the plugin's structure

### ISSUE THREAD

**Issue by azaozz** [WordPress/wp-autoupdates#34]
One requirement for WordPress Core feature plugins is that they need to "self-disable" after they are merged to core.

An easy way to do that is when the plugin's base-file (wp-autoupdates.php) has only the plugin's headers and a check whether the plugin has been merged, and all the functionality/code is in another file that gets included. For example the [Lazy Loading Feature Plugin](https://github.com/WordPress/wp-lazy-loading) was recently restructured to include a `functions.php` file for that reason.

**Comment by pbiron** [comment]
Looking through the functions in the plugin, I see 2 that are likely to be part of the merge proposal that could be checked for with `function_exists()` (like `wp-lazy-loading` does):

* wp_autoupdates_is_plugins_auto_update_enabled()
* wp_autoupdates_is_themes_auto_update_enabled()

However, the function names (in particular, the `wp_autoupdates_` prefix`) will likely change when merged into core.

How about we change those function name to:

* wp_is_plugins_auto_update_enabled()
* wp_is_themes_auto_update_enabled()

(but leave the prefix on all the other function names).

**Comment by audrasjb** [comment]
Yes I think our best option is to use `wp_is_plugins_auto_update_enabled()` 👍
