### ISSUE TITLE
Feature request: automatic delaying/postponing updates

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/wp-autoupdates#4]
_Migrated from: https://github.com/audrasjb/wp-autoupdates/issues/13
Previously opened by: @oldrup
Original description:_
>While I like automatic updates, and already uses several plugins from WordPress.org on not so prominent sites, I suggest you make it an option to delay/postpone updates for a while or maybe schedule them to specific days og time of day.
>
>a) For instance, I'd really prefer NOT to have major updates of themes and plugins being applied friday 4pm ;) Maybe auto-updated could be appled every tuesday at 9am where there are fewest visitors on my sites, and I'm available to fix any issues. Just an example, hope it makes sense.
>
>b) Sometimes, feature updates of community created plugins introduce new bugs. Both as a plugin consumer, and probably as a plugin author, I'd prefer updates to "drip release". Releasing a buggy update, and having it auto-install on millions of sites right after release, does not seem to be a ideal situation for neither the users nor the developer.
>
>c) Maybe updates could be tagged as feature updates, bugfixes and critical security updates, and the level of automation could differ accordingly?
>
>In any case - its a great feature and I'm sure it will help improving the security of WordPress installations. Thanks for making this a part of WordPress core.

**Comment by jeffpaul** [comment]
_Previously commented by: @audrasjb 
Original comment:_
>Hi @oldrup
>
>I think this features are not core territory but rather plugin territory.
But in my opinion, those are great question and I think WordPress Core should add some hooks to help other plugins that may want to add such an extra option.
>
>Thanks a lot for raising that :-)

**Comment by jeffpaul** [comment]
@audrasjb seems like we should re-title this issue as `Add hooks for automatic delaying/postponing updates` and re-label as `enhancement`, correct?

**Comment by pbiron** [comment]
> Maybe updates could be tagged as feature updates, bug fixes and critical security updates, and the level of automation could differ accordingly?

@oldrup Sorry I didn't say anything about this before now.  The above would require:

1. plugin/theme authors to semantic versioning (or some close approximation to it) and there is currently no requirement that they do so
2. changes the `Updates API` (which are out of our control)

There have been proposals to require semver before (e.g, https://meta.trac.wordpress.org/ticket/3428), but they haven't gone anywhere.

If you feel strongly about this, then I suggest you: 1) open a meta trac ticket to get the `Updates API` modifications necessary.

As for the scheduling ideas you made, see the comment I just added to #12.

Accordingly, I'm going to close this issue.
