### ISSUE TITLE
Green color information

### ISSUE THREAD

**Issue by davidperonne** [WordPress/wp-autoupdates#40]
The green color is so dark that it is not visible. Why not stay on black since it is only information and not a link?

**Comment by audrasjb** [comment]
Thank you for your feedback!
Since it's the only green available on WP-Admin styles, I think our best option would be to revert those strings to black.

**Comment by hedgefield** [comment]
I'd have to agree. The current green is sometimes hard to distinguish from black and this font size, and a lighter green would probably not pass accessibility guidelines. Besides, semantically I would say it is meta information, so black seems fine. The green feels a little out of place on those pages, although I understand why it was picked initially.

**Comment by audrasjb** [comment]
Thanks for your feedback @hedgefield !
