### ISSUE TITLE
Automatic theme update display defect

### ISSUE THREAD

**Issue by rodolphebertozzo** [WordPress/wp-autoupdates#41]
Hello,
I've noticed that the button to automatically update themes is not very nice (the icon and the button are a bit too underlined for my taste).
![bug](https://user-images.githubusercontent.com/56270626/78005867-7bc59600-733c-11ea-8928-7fa040040118.PNG)

**Comment by audrasjb** [comment]
Hi @rodolphebertozzo and thank you for your feedback!
Looks like a caching issue.
What if you clean you browser cache?

**Comment by rodolphebertozzo** [comment]
Hi,

I cleaned my browser cache (Opera). On the other browsers, this problem does not occur, I think it is strictly due to the Opera browser.

**Comment by rodolphebertozzo** [comment]
Hi,
This problem has been fixed since version 5.4 of Wordpress I have the impression, in any case, the display of the button has become correct on Opera as on other browsers.
