### ISSUE TITLE
First time test and feedback.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/wp-autoupdates#43]
I am doing an initial test to see what I notice...

Upon activating the plugin. 
I notice...the Automatic updates column. With the icon and Enable link.
I say wow cool. That looks nice and simple to relate to.

<img width="1209" alt="Screen Shot 2020-04-01 at 00 45 53" src="https://user-images.githubusercontent.com/5323259/78081964-27f59400-73b2-11ea-8465-475413f2443e.png">

I click Enable in the first plugin Akismet. It now changes to.

<img width="1208" alt="Screen Shot 2020-04-01 at 00 47 42" src="https://user-images.githubusercontent.com/5323259/78082060-6723e500-73b2-11ea-8b34-33d796febd5a.png">

Enable changes to 
"Auto-updates enabled" ---> In the color green
"Disable" ----> in the color red.

We now have three colors. Blue Enable text link. Green that it is enabled. Red for Disable.
It would be better to drop the green and keep it blue or black, and just keep the red Disable.
The green is somewhat similar the blue in color.

---

Next thought was hey I want to enable all of the plugins. Well perhaps not all but most of them.
I checked the Bulk Actions drop down.
<img width="309" alt="Screen Shot 2020-04-01 at 00 54 32" src="https://user-images.githubusercontent.com/5323259/78082471-63dd2900-73b3-11ea-8617-d6f91aa7a7db.png">

I selected all except one plugin. A notification showed up to let me know that 
"The selected plugins will now update automatically."

<img width="1036" alt="Screen Shot 2020-04-01 at 00 56 01" src="https://user-images.githubusercontent.com/5323259/78082567-abfc4b80-73b3-11ea-8c57-3298f566d646.png">

Hmm do we need a notification? I can easily see the change that happened in the Automatic updates column.

I closed the notification.

Now I reversed the action. I Disabled Auto updates for all the plugins.

Notification.
<img width="1043" alt="Screen Shot 2020-04-01 at 01 00 29" src="https://user-images.githubusercontent.com/5323259/78082813-35138280-73b4-11ea-84a6-6a18ded5e54f.png">

"The selected plugins won’t automatically update anymore."

The text feels a bit off. What about rephrasing to something like:
"The selected plugins will not any longer automatically update."

I now notice the not sure what the name is...an overview.
It is nice to see how many plugins are Auto-updates Enabled and Disabled.

<img width="1039" alt="Screen Shot 2020-04-01 at 01 06 09" src="https://user-images.githubusercontent.com/5323259/78083167-08139f80-73b5-11ea-96e6-0076897fdf16.png">

----

Going to the Themes screen.

<img width="1054" alt="Screen Shot 2020-04-01 at 01 08 07" src="https://user-images.githubusercontent.com/5323259/78083270-427d3c80-73b5-11ea-9533-10c4129a8dab.png">

Here there is not as obvious as in the plugin screen. As I have to click every theme and then Enable updates.

I clicked the orange update icon.

<img width="340" alt="Screen Shot 2020-04-01 at 01 09 48" src="https://user-images.githubusercontent.com/5323259/78083357-7e180680-73b5-11ea-8829-afc76b115d59.png">

It then jumped to the theme and I noticed it updated. I gave me two Updated notifications.

<img width="1034" alt="Screen Shot 2020-04-01 at 01 10 08" src="https://user-images.githubusercontent.com/5323259/78083395-9d169880-73b5-11ea-8fd4-d2b7cb5b2705.png">

I clicked the Enable automatic updates link.
It then automatically exited the theme screen to the general themes screen. I went back to the specific themes screen and noticed that Enabled had now turned to
"Disable automatic updates"

Should this instead be
"Automatic theme update is now enabled"
Hmm I do understand why it is as it is. As the user now needs to click the red text to disable the automatic update.

------

I went to Dashboard -> Updates.
Since all the plugins and themes are updated there was no message here.
I have no idea if there will be any update of the existing Updates screen.

**Comment by pbiron** [comment]
Thanx for all this review early on @paaljoachim.
