### ISSUE TITLE
Review the use of capitalization in strings

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/wp-autoupdates#44]
An example.

<img width="309" alt="Screen Shot 2020-04-01 at 00 54 32" src="https://user-images.githubusercontent.com/5323259/78083849-f7fcbf80-73b6-11ea-958c-9c7dace95cab.png">

Bulk Actions (capital B and capital A)
Enable auto-updates (could use a capital A)
Disable auto-updates (could use a capital A)

So in general go through and see where it needs a capital letter.

**Comment by pedro-mendonca** [comment]
In Gutenberg has started a discussion on this, and the conclusion was to start using `Sentence case`.
I guess it will probably start to populate to WP core in a near future.
So, probably leave it as `Enable auto-updates` / `Disable auto-updates`.

**Comment by paaljoachim** [comment]
Hey Pedro.

Thanks for the info! That is good to know.
That is one of the discussions I did not notice.

**Comment by pedro-mendonca** [comment]
Here is the link I found on one of the issues about that:
https://developer.wordpress.org/block-editor/contributors/document/copy-guide/#five-pay-attention-to-capitalization

**Comment by audrasjb** [comment]
Thanks for sharing this 🙂 
Sound clear to me, closing the issue as `wontfix`. Thanks!
