### ISSUE TITLE
Two updated! notifications in the themes screen

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/wp-autoupdates#45]
Themes screen

<img width="1054" alt="Screen Shot 2020-04-01 at 01 34 09" src="https://user-images.githubusercontent.com/5323259/78084589-e5838580-73b8-11ea-9b83-1befea85bc48.png">

I noticed when clicking the orange icon beside a new version available text. It jumps to the specific screen.

<img width="1038" alt="Screen Shot 2020-04-01 at 01 34 54" src="https://user-images.githubusercontent.com/5323259/78084623-fe8c3680-73b8-11ea-8c92-869bedd7697e.png">

Then

<img width="1037" alt="Screen Shot 2020-04-01 at 01 35 15" src="https://user-images.githubusercontent.com/5323259/78084643-0b108f00-73b9-11ea-89f0-10a4df938f54.png">

<img width="1196" alt="Screen Shot 2020-04-01 at 01 36 24" src="https://user-images.githubusercontent.com/5323259/78084705-36937980-73b9-11ea-8549-d24ac39b5d25.png">

I had before updating the themes deactivated all plugins except the WordPress auto-updates plugin.

This has happened on two local sites.

One had Twenty Twenty theme activated the other another theme.
Desktop Server
Chrome
Mac OSX 10.15.4

**Comment by bookdude13** [comment]
I thought #32 fixed this, but perhaps I was wrong. Are you using plugin version 0.4.0?

**Comment by paaljoachim** [comment]
Yeah. I tested last night with the newest version. 0.4.0.

**Comment by bookdude13** [comment]
It looks like this happens when you click update on the list of themes page, then you go into the theme details. In that case it's happening to me even when this plugin is disabled, so this is a problem in core. I made a Trac ticket to track this: https://core.trac.wordpress.org/ticket/49771

**Comment by pbiron** [comment]
@bookdue13 Thanx for opening the trac ticket!
