### ISSUE TITLE
Rephrase "The selected plugins won’t automatically update anymore."

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/wp-autoupdates#46]
Regarding this text.

<img width="1043" alt="Screen Shot 2020-04-01 at 01 00 29" src="https://user-images.githubusercontent.com/5323259/78084988-eb2d9b00-73b9-11ea-8803-aa5d03e0ee4f.png">

"The selected plugins won’t automatically update anymore."

The text feels a bit off. What about rephrasing to something like:
"The selected plugins will not automatically update."
Or
"The selected plugins will not automatically update any longer."
Or
"The selected plugins will not any longer be automatically updated."

**Comment by pedro-mendonca** [comment]
Suggestion for both bulk action notices:

- `Auto-update was disabled for the selected plugins.`
- `Auto-update was enabled for the selected plugins.`
