### ISSUE TITLE
Clicking Enable/Disable the focus jumps to the top of the screen.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/wp-autoupdates#47]
The following happens with clicking Enable/Disable.
I do think it is a built in behavior and I am not sure anything can be done with it in relation to this plugin.
As the same thing happens with activating/deactivating a plugin.

![Focus-jumps-to-top-of-screen](https://user-images.githubusercontent.com/5323259/78178054-567d7880-745f-11ea-97d9-bed615e49758.gif)

**Comment by ronalfy** [comment]
If Ajax isn't used, perhaps we can use some JS that auto-scrolls the user or have an anchor that can be targeted? I haven't had much luck with this from a UX perspective, but it's something to consider.

**Comment by pbiron** [comment]
> If Ajax isn't used, perhaps we can use some JS that auto-scrolls the user or have an anchor that can be targeted?

I wouldn't mind if that mind that **if all links in all list tables behaved that way**, but doing it just for the `Enable/Disable`  here would seem odd to me.

So, I would suggest that those who think that would be a good idea should open a trac ticket for it.

**Comment by paaljoachim** [comment]
Thanks for closing the issue Paul! @pbiron 
Time for me to put together a trac issue.
Clicking the "update now" a moving spinner is seen, the screen does not jump to the top and a plugin is updated.
Clicking Activate/Deactivate the screen jumps to the top. So right now there are two methods in this Installed Screen.
