### ISSUE TITLE
Testing the plugin in a Multisite Network

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/wp-autoupdates#51]
I have installed WP Auto Updates in a multisite Network.

Here is a run through.

The plugins screen.

![Screen Shot 2020-04-03 at 01 34 03](https://user-images.githubusercontent.com/5323259/78309466-4c38a880-754b-11ea-9701-7b74cb87086b.png)

I turned on the Auto Update for the WP Auto Updates plugin.

![Screen Shot 2020-04-03 at 01 35 49](https://user-images.githubusercontent.com/5323259/78309539-843feb80-754b-11ea-9961-bddf6fdbdf08.png)

I really liked to see when it would auto update.

I went to the Themes screen, and as I have not used a multisite for a while it surprised me that this did not look similar to a regular single site themes screen.

![Screen Shot 2020-04-03 at 01 37 34](https://user-images.githubusercontent.com/5323259/78309621-cc5f0e00-754b-11ea-9aab-930b689ab122.png)

I enabled two themes and noticed the blue Disable link. Which should be red.

![Screen Shot 2020-04-03 at 01 39 02](https://user-images.githubusercontent.com/5323259/78309705-0d572280-754c-11ea-82a1-0abc92cc1838.png)

----

I went back and updated WP Auto Updates plugin.

![Screen Shot 2020-04-03 at 01 44 52](https://user-images.githubusercontent.com/5323259/78309973-cddd0600-754c-11ea-958d-53c6b28ba9de.png)

Should the green color in "Auto-updates enabled" be the same color as the green checkmark next to the Updated text? Probably not as the green checkmark seems to contain a lighter green then the "Auto-updates enabled" text.

**Comment by ronalfy** [comment]
Thanks for testing in MS @paaljoachim! That's the hardest use-case for Easy Updates Manager. Looks like everything looks amazing.

**Comment by paaljoachim** [comment]
Testing out the 0.5.0 version.

Network installed plugin screen.
![Screen Shot 2020-04-16 at 10 47 36](https://user-images.githubusercontent.com/5323259/79438602-090f1880-7fd4-11ea-908e-4a8a045e3eb9.png)

Network installed themes screen.
![Screen Shot 2020-04-16 at 10 48 41](https://user-images.githubusercontent.com/5323259/79438648-17f5cb00-7fd4-11ea-9c14-d727fde986f9.png)

@audrasjb @pbiron

**Comment by pbiron** [comment]
@paaljoachim Thanx for the testing.  I'm going to close this.
