### ISSUE TITLE
Network Themes page has blue color Disable text

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/wp-autoupdates#52]
As I just tested out a multisite and WP Auto Updates. I noticed that the Themes screen shows a blue color with the Disable text. It should be red.

![Screen Shot 2020-04-03 at 01 39 02](https://user-images.githubusercontent.com/5323259/78310266-a9cdf480-754d-11ea-8cac-f9cc7e9bf63f.png)

**Comment by audrasjb** [comment]
Thanks for spotting this @paaljoachim. 
#54 should fix the issue.

**Comment by pbiron** [comment]
I'm not sure we should "fix" this...as I think the use of red for the disable link on the plugins screen is "wrong".

`Disable` auto-updates to me is analogous to `Deactivate` for plugins and the row action link for that is not red.  Red is generally reserved for destructive actions (e.g., `Delete`) and I don't think disabling auto-updates is destructive.

**Comment by pbiron** [comment]
That is, I agree that if we keep the disable link red on other screens then it should be read on the themes screen as well (for consistency).  But I think the more consistent think would be to make it blue (or black, or whatever the design review suggests) on all screens.

**Comment by paaljoachim** [comment]
I am looking into resources right now, as there are likely color guidelines for this exact thing.

**Comment by paaljoachim** [comment]
Btw just looking at the regular Installed plugins screen as well as the themes screen to see how colors are used today.

Red is used when deleting a plugin or deleting a theme. As Paul says Red = destructive.
Blue is used for activating and deactivating a plugin.
Plugin titles are black.

Based on the existing method.
Disable and Enable should both be blue.

**Comment by paaljoachim** [comment]
I played with it in Figma, and here is what it looks like when the first disable text is blue.
We need to bring this up again in the design channel.

![Plugins screen](https://user-images.githubusercontent.com/5323259/78408817-64223200-7608-11ea-8b74-23b6cd103b9a.jpg)


I made a specific issue with focus on color usage:
https://github.com/WordPress/wp-autoupdates/issues/56
