### ISSUE TITLE
Add filter to control whether the email notification is sent?

### ISSUE THREAD

**Issue by pbiron** [WordPress/wp-autoupdates#55]
Core has 2 filters that control whether core update notifications are sent:

* [send_core_update_notification_email](https://developer.wordpress.org/reference/hooks/send_core_update_notification_email/)
* [auto_core_update_send_email](https://developer.wordpress.org/reference/hooks/auto_core_update_send_email/)

Should we add the equivalents for plugin/theme auto-updates?

**Comment by audrasjb** [comment]
Yes I think so. I can work on a pull request for this if you want

**Comment by pbiron** [comment]
> Yes I think so. I can work on a pull request for this if you want

That be great, thanx!
