### ISSUE TITLE
HTML Abstraction

### ISSUE THREAD

**Issue by ronalfy** [WordPress/wp-autoupdates#64]
The goal of this issue is to bring aware that certain phrases can be abstracted out for re-use, particularly if we're wanting to allow Ajax enabling/disabling of assets. This is so the Ajax HTML return and default HTML return return the same markup and to make it future proof.

At this point, it's very likely this will break things, but I think it's worth the effort to do this even if Ajax isn't used.

Related #59 

PR Related https://github.com/WordPress/wp-autoupdates/pull/61

**Comment by pbiron** [comment]
Closing as this is no longer relevant, given other PRs that have been merged.

**Comment by pbiron** [comment]
Closing as this is no longer relevant, given other PRs that have been merged.
