### ISSUE TITLE
Enable/Disable links for Themes should not appear in the Theme Details modal on subsites in a multisite

### ISSUE THREAD

**Issue by pbiron** [WordPress/wp-autoupdates#67]
Why?  Because when an admin user clicks on those links they get a `wp_die()` screen that says:

> Please connect to your network admin to manage themes automatic updates.

If the link won't actually work, then it shouldn't be displayed.  It is the same reasoning behind the entire `Automatic updates` not displaying on the Plugins screen of a subsite in a multisite.

**Comment by pbiron** [comment]
As an aside, about 10 days ago I mentioned the following in [#slack](https://wordpress.slack.com/archives/CULBN711P/p1585164755023800)

> I just noticed that in a multisite, you are allowed to update themes (manually, not talking about auto-update) on the `themes.php` screen within a sub-site...whereas, for plugins you have to be on the network/plugins.php screen.  Does anyone else thing that is a "bug" in core (i.e., shouldn't you have to be on `network/themes.php`)?

I think that's a bug in core because plugins can only be updated from the `Network Admin > Plugins` screen).

Does anyone think I should open a trac ticket for that?

**Comment by pbiron** [comment]
Thanx @JJJ, will do.

**Comment by pbiron** [comment]
The core bug has been reported in [Trac ticket #49831](https://core.trac.wordpress.org/ticket/49831)...but this issue is still a bug in this plugin :-)

**Comment by rodolphebertozzo** [comment]
For the milestone 0.5 ?
