### ISSUE TITLE
Is the "cycle" icon necessary?

### ISSUE THREAD

**Issue by audrasjb** [WordPress/wp-autoupdates#71]
This point was raised by @nrqnscz in our [call for testing](https://make.wordpress.org/test/2020/04/01/help-testing-wordpress-auto-updates-feature-plugin-version-0-4/#comment-1259):

> I’m not sure the “cycle” icon is necessary. It appears on every row and it can be too much. Also, no other link in that table is using an icon, so it feels a bit out of place. Have you tried without it?

**Comment by wittwitsan** [comment]
Here's the screenshot of no "cycle" icon.
![Screen Shot 2020-04-15 at 00 07 32](https://user-images.githubusercontent.com/426383/79253296-2a291980-7ead-11ea-99b6-c96260839ed1.png)

**Comment by rodolphebertozzo** [comment]
If it can optimize the speed of the plugin, yes why not, but if it doesn't have a positive impact on performance, you might as well keep the icon for the design aspect.

**Comment by audrasjb** [comment]
As per today’s team meeting, the decision is to remove dashicons for a cleaner and more simple UI.
