### ISSUE TITLE
Use a more descriptive term instead of "enable" single word

### ISSUE THREAD

**Issue by audrasjb** [WordPress/wp-autoupdates#72]
This point was raised by @nrqnscz in our [call for testing](https://make.wordpress.org/test/2020/04/01/help-testing-wordpress-auto-updates-feature-plugin-version-0-4/#comment-1259):

> Having just the single word “Enable” appear on that column, can confuse those who don’t read the column heading thinking that it refers to the activation of the plugin instead. I know we are using different words on purpose to avoid that confusion (Activate vs. Enable), but I’m wondering if having a more descriptive link could help avoid any possible misunderstandings.
> It might feel that “Enable auto-updates” can be too long, but I prefer to be overly obvious. We are already doing something similar with the “Visit plugin site” link that also appears on every row.

**Comment by wittwitsan** [comment]
I agree to change the word "Enable", especially on the mobile device that can confuse the users.

![Screen Shot 2020-04-08 at 01 46 56](https://user-images.githubusercontent.com/426383/79254270-ae2fd100-7eae-11ea-9412-9a5adc52ce2e.png)

**Comment by audrasjb** [comment]
Thanks for the screenshot 👍 
As per today’s meeting, let's replace "Enable" string with "Enable auto-updates" for better clarity.
