### ISSUE TITLE
Phrase: Selected plugins will no longer be auto-updated need to also be adjusted for single plugin.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/wp-autoupdates#80]
With the new phrase:
"Selected plugins will no longer be auto-updated."
and
"Selected plugins will be auto-updated."

The above phrase also shows up when a single plugin is clicked for Enable auto-updates / or Disable auto-updates.

If possible. Adjust disabling or enabling auto update for one plugin have this phrase:
"Selected plugin will no longer be auto-updated."
and
"Selected plugin will be auto-updated."

Removing the s in plugins so it becomes plugin when a single plugin is affected.

**Comment by pbiron** [comment]
This was indirectly addressed in #124.
