### ISSUE TITLE
Allow to Enable/Disable Auto-updates features through constants

### ISSUE THREAD

**Issue by mahnunchik** [WordPress/wp-autoupdates#82]
Hi,

I understand the need of the auto-updates feature and corresponding UI. There are many use cases for `mouse-click-click` lovers users, for newbies, and for websites that not critical for a little downtime in case of broken update/rollback. I don't know exact numbers, but my assumption that it is about 80% of active users.

But there are `console` lovers, surprise 🐳 Usually they prefer to configure through constants in the code, config files or environment variables.

**Main idea:** let's make the plugin compatible with configuration through the code too.

- [ ] Allow to Enable/Disable Auto-updates features through constants

Actually it is already done since WP 3.7 but according to thread here https://core.trac.wordpress.org/ticket/48850 there are some misunderstanding (even for developers) what each constant should do and should not do.

I've found explanation in two different pages and they are not linked between:

* https://wordpress.org/support/article/editing-wp-config-php/
* https://wordpress.org/support/article/configuring-automatic-background-updates/

- [ ] I think it makes sense to improve the documentation (at least add links between them).
- [ ] Also it would be nice to cover in the plugin documentation different plugin behaviour dependent on that constant. 
- [ ] Show/Hide corresponding admin/plugin UI depending on settings.

**Comment by pbiron** [comment]
Thanx for this @mahnunchik.

We have started to gather a list of the constants and hooks that will need to be documented when this feature plugin is merged into core at #20.

**Comment by pbiron** [comment]
During the meeting on May 5, it was decided to [remove the constants](https://wordpress.slack.com/archives/CULBN711P/p1588699952239600), and that was accomplished in #110.

So I'm closing this issue.
