### ISSUE TITLE
AJAX Error Handling

### ISSUE THREAD

**Issue by ronalfy** [WordPress/wp-autoupdates#87]
When an inevitable Ajax call fails, right now it is just an `alert`.

I'm trying to come up with suggestions where Ajax enabling/disabling of auto-updates fails gracefully.

Any ideas?

**Comment by pbiron** [comment]
Something like `__( 'Enabling auto-update failed: %s', 'wp-autoupdates' )`, where the `%s` is the error that happened on the PHP side?

**Comment by audrasjb** [comment]
Or what about something like this?

![Capture d’écran 2020-04-21 à 22 24 34](https://user-images.githubusercontent.com/1590998/79910427-fd31b500-841e-11ea-9bfd-9e598d215d2f.png)

**Comment by audrasjb** [comment]
Ah yes @pbiron a general notice on the top of the screen would also works.

**Comment by pbiron** [comment]
I was thinking more like your screenshot, but with the error text replacing the `Enable/Disable` link (instead of below it), which is what shiny updates does.  That requires the screen to be reloaded to try again, so maybe having the error text below the link would be better.
