### ISSUE TITLE
Undefined index SERVER_NAME from email notifications 

### ISSUE THREAD

**Issue by afragen** [WordPress/wp-autoupdates#89]
I have been seeing the following error in my logs and I believe it's related to the email notification from an autoupdate.

`PHP Notice Undefined index: SERVER_NAME in /sites/mysite.com/html/wp-includes/pluggable.php on line 331 `

I believe this originates here, though I'm not certain.
https://github.com/WordPress/wp-autoupdates/blob/4223e42aa837e6b0a8d40306b9e13fda9e6ea781/functions.php#L1114

**Comment by afragen** [comment]
An additional point. The site is set to send email via WP Mail SMTP and is set to email via my iCloud address. Not sure if that makes a difference. And yes, the email is getting sent and received.

**Comment by pbiron** [comment]
That is where the email send is initiated, but the link where the warning is generated is within `wp_mail()`, which suggests that something is misconfig'd at the server level (i.e., apache/nginx)?  That is, the web server should be setting `$_SERVER['SERVER_NAME`]`, which doesn't seem to be happening.

Is this on your local machine (I.e., with Local By Flywheel, etc) or on a "real" host?

**Comment by afragen** [comment]
It's on a real host, a DO droplet from SpinupWP.

**Comment by afragen** [comment]
I set up some debugging stuff on the site via a hook into `wp_autoupdates_notifications_email` to write `$_REQUEST` to the error.log. 

I also turned down a version number  to force an update. We shall see what it shows.

**Comment by afragen** [comment]
I think it might be related to the fact that WP-Cron is off and running on a real cronjob every minute. I now see in the logs that `$_SERVER['SERVER_NAME']` is not set during this cronjob that calls, `wp cron event --due-now`

Hmm.

**Comment by pbiron** [comment]
when you have received the email, what's in the `From: ` header?  Because that's what the `$_SERVER['SERVER_NAME']` is used for by `wp_mail()` (when the caller hasn't set a `From: ` header.

**Comment by afragen** [comment]
The `From: ` header contains the values I have for WP Mail SMTP. I’m guessing that at some point after the error WP Mail SMTP hijacks wp_mail().

**Comment by afragen** [comment]
So I think it's definitely related to having WP-Cron off and running as above. I set the following filter.

```php
add_filter(
	'wp_autoupdates_notifications_email',
	function ($email) {
		//$email['headers'][] = 'From: wordpress@' . parse_url(site_url(), PHP_URL_HOST);
		$_SERVER['SERVER_NAME'] = isset($_SERVER['SERVER_NAME']) ? $_SERVER['SERVER_NAME'] : parse_url(site_url(), PHP_URL_HOST);
		error_log(var_export($email, true));
		error_log('SERVER_NAME: ' . var_export($_SERVER['SERVER_NAME'], true));
		return $email;
	},
	10,
	1
);
```
and got the following results.

```
[23-Apr-2020 09:01:08 UTC] PHP Notice Undefined index: SERVER_NAME in /sites/thefragens.net/files/wp-includes/pluggable.php on line 331
[23-Apr-2020 09:01:08 UTC] array ( 'to' => 'andy@thefragens.com', 'subject' => '[Just a test site] Some plugins or themes were automatically updated', 'body' => 'The following plugins were successfully updated: - Query Monitor If you experience any issues or need support, the volunteers in the WordPress.org support forums may be able to help. https://wordpress.org/support/forums/ The WordPress Team', 'headers' => '', )
[23-Apr-2020 09:01:08 UTC] SERVER_NAME: 'thefragens.net'
```

It seems something is calling `wp_mail()` at least once prior to the filter.  🤷🏻‍♂️

**Comment by TimothyBJacobs** [comment]
Fairly certain this is https://core.trac.wordpress.org/ticket/25239

**Comment by afragen** [comment]
It is @TimothyBJacobs. I was just looking at that ticket.

Closed as duplicate of https://core.trac.wordpress.org/ticket/25239
