### ISSUE TITLE
When saving with AJAX, calculate the number of plugins and themes with enablerd autoupdate from js

### ISSUE THREAD

**Issue by azaozz** [WordPress/wp-autoupdates#97]
This is for updating the "Auto-updates" links at the top:

![Screen Shot 2020-05-01 at 16 36 17](https://user-images.githubusercontent.com/743931/80848952-fb5bb480-8bc9-11ea-9295-41914aa709e5.png)

Doesn't seem needed to recalculate the enabled/disabled numbers on every AJAX request as the change is either +/-1 or 0.

**Comment by pbiron** [comment]
Fixed in #99.
